/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppOnboardingRouteImport } from './routes/app_.onboarding'
import { Route as AppTransfersRouteImport } from './routes/app.transfers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppAuditLogRouteImport } from './routes/app.audit-log'
import { Route as AppComplianceAgentTxIdRouteImport } from './routes/app.compliance.agent.$txId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/app_/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogRoute = AppAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceAgentTxIdRoute = AppComplianceAgentTxIdRouteImport.update({
  id: '/agent/$txId',
  path: '/agent/$txId',
  getParentRoute: () => AppComplianceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/audit-log': typeof AppAuditLogRoute
  '/app/compliance': typeof AppComplianceRouteWithChildren
  '/app/overview': typeof AppOverviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/compliance/agent/$txId': typeof AppComplianceAgentTxIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/audit-log': typeof AppAuditLogRoute
  '/app/compliance': typeof AppComplianceRouteWithChildren
  '/app/overview': typeof AppOverviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app': typeof AppIndexRoute
  '/app/compliance/agent/$txId': typeof AppComplianceAgentTxIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/audit-log': typeof AppAuditLogRoute
  '/app/compliance': typeof AppComplianceRouteWithChildren
  '/app/overview': typeof AppOverviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/transfers': typeof AppTransfersRoute
  '/app_/onboarding': typeof AppOnboardingRoute
  '/app/': typeof AppIndexRoute
  '/app/compliance/agent/$txId': typeof AppComplianceAgentTxIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/audit-log'
    | '/app/compliance'
    | '/app/overview'
    | '/app/settings'
    | '/app/transfers'
    | '/app/onboarding'
    | '/app/'
    | '/app/compliance/agent/$txId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/audit-log'
    | '/app/compliance'
    | '/app/overview'
    | '/app/settings'
    | '/app/transfers'
    | '/app/onboarding'
    | '/app'
    | '/app/compliance/agent/$txId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/audit-log'
    | '/app/compliance'
    | '/app/overview'
    | '/app/settings'
    | '/app/transfers'
    | '/app_/onboarding'
    | '/app/'
    | '/app/compliance/agent/$txId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app_/onboarding': {
      id: '/app_/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transfers': {
      id: '/app/transfers'
      path: '/transfers'
      fullPath: '/app/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit-log': {
      id: '/app/audit-log'
      path: '/audit-log'
      fullPath: '/app/audit-log'
      preLoaderRoute: typeof AppAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance/agent/$txId': {
      id: '/app/compliance/agent/$txId'
      path: '/agent/$txId'
      fullPath: '/app/compliance/agent/$txId'
      preLoaderRoute: typeof AppComplianceAgentTxIdRouteImport
      parentRoute: typeof AppComplianceRoute
    }
  }
}

interface AppComplianceRouteChildren {
  AppComplianceAgentTxIdRoute: typeof AppComplianceAgentTxIdRoute
}

const AppComplianceRouteChildren: AppComplianceRouteChildren = {
  AppComplianceAgentTxIdRoute: AppComplianceAgentTxIdRoute,
}

const AppComplianceRouteWithChildren = AppComplianceRoute._addFileChildren(
  AppComplianceRouteChildren,
)

interface AppRouteChildren {
  AppAuditLogRoute: typeof AppAuditLogRoute
  AppComplianceRoute: typeof AppComplianceRouteWithChildren
  AppOverviewRoute: typeof AppOverviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditLogRoute: AppAuditLogRoute,
  AppComplianceRoute: AppComplianceRouteWithChildren,
  AppOverviewRoute: AppOverviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
